import { TCompany } from './functions/vTubersConfigs';

type TTwoDigit = `${number}${number}`;
type TDateString = `20${TTwoDigit}-${TTwoDigit}-${TTwoDigit}`;
type TDatetimeString = `${TDateString} ${TTwoDigit}:${TTwoDigit}`;

type TVtuber = {
  key: string;
  name: string;
  height: number;
  other: string;
  group: string;
  sort: number;
  twitter: `https://x.com/${string}`;
  youtube: `https://www.youtube.com/${string}`;
  company: TCompany;
  birthday: `${number}/${number}`;
  graduation?: TDateString | TDatetimeString;
  debuts: {
    date: TDateString | TDatetimeString;
    description: string;
  }[];
  illustrator?: {
    name: string;
    twitter: `https://x.com/${string}`;
    role?: string;
  }[];
};

export const vTubers: TVtuber[] = [
  {
    key: 'sora',
    name: 'ときのそら',
    debuts: [{ date: '2017-09-07', description: '初配信日' }],
    birthday: '5/15',
    height: 160,
    other: '',
    group: '0期生',
    company: 'hololive',
    sort: 100.0,
    twitter: 'https://x.com/tokino_sora',
    youtube: 'https://www.youtube.com/channel/UCp6993wxpyDPHUpavwDFqgg',
    illustrator: [
      {
        name: 'おるだん',
        twitter: 'https://x.com/ordan',
      },
    ],
  },
  {
    key: 'azki',
    name: 'Azki',
    debuts: [
      { date: '2018-11-15', description: '個人として活動開始' },
      { date: '2019-05-19', description: 'イノナカ加入日' },
      { date: '2022-04-01', description: 'ホロライブ加入日' },
    ],
    birthday: '7/1',
    height: 168,
    other: '',
    group: '0期生',
    company: 'hololive',
    sort: 100.03,
    twitter: 'https://x.com/AZKi_VDiVA',
    youtube: 'https://www.youtube.com/channel/UC0TXe_LYZ4scaW2XMyi5_kw',
  },
  {
    key: 'roboco',
    name: 'ロボコさん',
    debuts: [{ date: '2018-03-04', description: 'デビュー日' }],
    birthday: '5/23',
    height: 154,
    other: '',
    group: '0期生',
    company: 'hololive',
    sort: 100.01,
    twitter: 'https://x.com/robocosan',
    youtube: 'https://www.youtube.com/channel/UCDqI2jOz0weumE8s7paEk6g',
    illustrator: [
      {
        name: '安曇アキタケ',
        twitter: 'https://x.com/akitake_a',
      },
    ],
  },
  {
    key: 'miko',
    name: 'さくらみこ',
    debuts: [
      { date: '2018-08-01', description: '｢さくらみこProject」として活動開始' }, // 公式サイトにデビュー日として記載
      { date: '2018-12-25', description: 'ホロライブ加入日' },
    ],
    birthday: '3/5',
    height: 152,
    other: '',
    group: '0期生',
    company: 'hololive',
    sort: 100.02,
    twitter: 'https://x.com/sakuramiko35',
    youtube: 'https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA',
    illustrator: [
      {
        name: '田中雄一',
        twitter: 'https://x.com/momoko',
        role: 'キャラクターデザイン',
      },
      {
        name: 'おるだん',
        twitter: 'https://x.com/ordan',
        role: '新衣装デザイン',
      },
    ],
  },
  {
    key: 'fbk',
    name: '白上フブキ',
    debuts: [{ date: '2018-06-01 00:02', description: '初配信日' }],
    birthday: '10/5',
    height: 155,
    other: '',
    group: '1期生,ゲーマーズ',
    company: 'hololive',
    sort: 101.03,
    twitter: 'https://x.com/shirakamifubuki',
    youtube: 'https://www.youtube.com/channel/UCdn5BQ06XqgXoAxIhbqw5Rg',
    illustrator: [
      {
        name: '凪白みと',
        twitter: 'https://x.com/lemon_mito',
      },
    ],
  },
  {
    key: 'maturi',
    name: '夏色まつり',
    debuts: [{ date: '2018-06-01 00:03', description: 'デビュー日' }],
    birthday: '7/22',
    height: 152,
    other: '',
    group: '1期生',
    company: 'hololive',
    sort: 101.04,
    twitter: 'https://x.com/natsuiromatsuri',
    youtube: 'https://www.youtube.com/channel/UCQ0UDLQCjY0rmuxCDE38FGg',
  },
  {
    key: 'meru',
    name: '夜空メル',
    debuts: [{ date: '2018-05-13', description: 'デビュー日' }],
    birthday: '10/31',
    height: 154,
    other: '',
    group: '1期生',
    company: 'hololive',
    sort: 101.0,
    twitter: 'https://x.com/yozoramel',
    youtube: 'https://www.youtube.com/channel/UCD8HOxPs4Xvsm8H0ZxXGiBw',
  },
  {
    key: 'haato',
    name: '赤井はあと',
    debuts: [{ date: '2018-06-02', description: 'デビュー日' }],
    birthday: '8/10',
    height: 154,
    other: '',
    group: '1期生',
    company: 'hololive',
    sort: 101.02,
    twitter: 'https://x.com/akaihaato',
    youtube: 'https://www.youtube.com/channel/UC1CfXB_kRs3C-zaeTG3oGyg',
  },
  {
    key: 'akirose',
    name: 'アキ・ローゼンタール',
    debuts: [{ date: '2018-06-01 00:00', description: 'デビュー日' }],
    birthday: '2/17',
    height: 162,
    other: '',
    group: '1期生',
    company: 'hololive',
    sort: 101.01,
    twitter: 'https://x.com/akirosenthal',
    youtube: 'https://www.youtube.com/channel/UCFTLzh12_nrtzqBPsTCqenA',
  },
  {
    key: 'aqua',
    name: '湊あくあ',
    debuts: [{ date: '2018-08-08', description: 'デビュー日' }],
    graduation: '2024-08-28',
    birthday: '12/01',
    height: 148,
    other: '体重：44.5kg',
    group: '2期生',
    company: 'hololive',
    sort: 102.0,
    twitter: 'https://x.com/minatoaqua',
    youtube: 'https://www.youtube.com/channel/UC1opHUrw8rvnsadT-iGp7Cg',
  },
  {
    key: 'choco',
    name: '癒月ちょこ',
    debuts: [{ date: '2018-09-04', description: 'デビュー日' }],
    birthday: '2/14',
    height: 165,
    other: '',
    group: '2期生',
    company: 'hololive',
    sort: 102.03,
    twitter: 'https://x.com/yuzukichococh',
    youtube: 'https://www.youtube.com/channel/UC1suqwovbL1kzsoaZgFZLKg',
  },
  {
    key: 'ayame',
    name: '百鬼あやめ',
    debuts: [{ date: '2018-09-03', description: 'デビュー日' }],
    birthday: '12/13',
    height: 152,
    other: '',
    group: '2期生',
    company: 'hololive',
    sort: 102.02,
    twitter: 'https://x.com/nakiriayame',
    youtube: 'https://www.youtube.com/channel/UC7fk0CB07ly8oSl0aqKkqFg',
  },
  {
    key: 'shion',
    name: '紫咲シオン',
    debuts: [{ date: '2018-08-17', description: 'デビュー日' }],
    graduation: '2025-04-26',
    birthday: '12/8',
    height: 145,
    other: '',
    group: '2期生',
    company: 'hololive',
    sort: 102.01,
    twitter: 'https://x.com/murasakishionch',
    youtube: 'https://www.youtube.com/channel/UCXTpFs_3PqI41qX2d9tL2Rw',
  },
  {
    key: 'subaru',
    name: '大空スバル',
    debuts: [{ date: '2018-09-16', description: 'デビュー日' }],
    birthday: '7/2',
    height: 154,
    other: '',
    group: '2期生',
    company: 'hololive',
    sort: 102.05,
    twitter: 'https://x.com/oozorasubaru',
    youtube: 'https://www.youtube.com/channel/UCvzGlP9oQwU--Y0r9id_jnA',
  },
  {
    key: 'mio',
    name: '大神ミオ',
    debuts: [{ date: '2018-12-07', description: 'デビュー日' }],
    birthday: '8/20',
    height: 165,
    other: '',
    group: 'ゲーマーズ',
    company: 'hololive',
    sort: 102.5,
    twitter: 'https://x.com/ookamimio',
    youtube: 'https://www.youtube.com/channel/UCp-5t9SrOQwXMU7iIjQfARg',
  },
  {
    key: 'okayu',
    name: '猫又おかゆ',
    debuts: [{ date: '2019-04-06', description: 'デビュー日' }],
    birthday: '2/22',
    height: 152,
    other: '',
    group: 'ゲーマーズ',
    company: 'hololive',
    sort: 102.51,
    twitter: 'https://x.com/nekomataokayu',
    youtube: 'https://www.youtube.com/channel/UCvaTdHTWBGv3MKj3KVqJVCw',
  },
  {
    key: 'korone',
    name: '戌神ころね',
    debuts: [{ date: '2019-04-13', description: 'デビュー日' }],
    birthday: '10/1',
    height: 156,
    other: '',
    group: 'ゲーマーズ',
    company: 'hololive',
    sort: 102.52,
    twitter: 'https://x.com/inugamikorone',
    youtube: 'https://www.youtube.com/channel/UChAnqc_AY5_I3Px5dig3X1Q',
  },
  {
    key: 'flare',
    name: '不知火フレア',
    debuts: [{ date: '2019-08-07', description: 'デビュー日' }],
    birthday: '4/2',
    height: 158,
    other: '',
    group: '3期生',
    company: 'hololive',
    sort: 103.02,
    twitter: 'https://x.com/shiranuiflare',
    youtube: 'https://www.youtube.com/channel/UCvInZx9h3jC2JzsIzoOebWg',
  },
  {
    key: 'noel',
    name: '白銀ノエル',
    debuts: [{ date: '2019-08-08', description: 'デビュー日' }],
    birthday: '11/24',
    height: 158,
    other: '胸：Kカップ',
    group: '3期生',
    company: 'hololive',
    sort: 103.03,
    twitter: 'https://x.com/shiroganenoel',
    youtube: 'https://www.youtube.com/channel/UCdyqAaZDKHXg4Ahi7VENThQ',
  },
  {
    key: 'marine',
    name: '宝鐘マリン',
    debuts: [{ date: '2019-08-11', description: 'デビュー日' }],
    birthday: '7/30',
    height: 150,
    other: '',
    group: '3期生',
    company: 'hololive',
    sort: 103.04,
    twitter: 'https://x.com/houshoumarine',
    youtube: 'https://www.youtube.com/channel/UCCzUftO8KOVkV4wQG1vkUvg',
  },
  {
    key: 'pekora',
    name: '兎田ぺこら',
    debuts: [{ date: '2019-07-17', description: 'デビュー日' }],
    birthday: '1/12',
    height: 153,
    other: '',
    group: '3期生',
    company: 'hololive',
    sort: 103.0,
    twitter: 'https://x.com/usadapekora',
    youtube: 'https://www.youtube.com/channel/UC1DCedRgGHBdm81E1llLhOQ',
  },
  {
    key: 'rushia',
    name: '潤羽るしあ',
    debuts: [{ date: '2019-07-18', description: 'デビュー日' }],
    birthday: '1/22',
    height: 143,
    other: '',
    group: '3期生',
    company: 'hololive',
    sort: 103.01,
    twitter: 'https://x.com/uruharushia',
    youtube: 'https://www.youtube.com/channel/UCl_gCybOJRIgOXw6Qb4qJzQ',
  },
  {
    key: 'suisei',
    name: '星街すいせい',
    debuts: [
      { date: '2018-03-22', description: '個人としてYoutubeで活用開始' }, // 公式サイトにデビュー日として記載。twitterでの活動開始は3/18
      { date: '2019-05-19', description: 'イノナカ加入日' },
      { date: '2019-12-01', description: 'ホロライブ加入日' },
    ],
    birthday: '3/22',
    height: 160,
    other: '',
    group: '0期生',
    company: 'hololive',
    sort: 100.05,
    twitter: 'https://x.com/suisei_hosimati',
    youtube: 'https://www.youtube.com/channel/UC5CwaMl1eIgY8h02uZw7u8A',
  },
  {
    key: 'kanata',
    name: '天音かなた',
    debuts: [{ date: '2019-12-27', description: 'デビュー日' }],
    birthday: '4/22',
    height: 149,
    other: '',
    group: '4期生',
    company: 'hololive',
    sort: 104.0,
    twitter: 'https://x.com/amanekanatach',
    youtube: 'https://www.youtube.com/channel/UCZlDXzGoo7d44bwdNObFacg',
  },
  {
    key: 'coco',
    name: '桐生ココ',
    debuts: [{ date: '2019-12-28', description: 'デビュー日' }],
    graduation: '2021-07-01',
    birthday: '6/17',
    height: 180,
    other: '',
    group: '4期生',
    company: 'hololive',
    sort: 104.01,
    twitter: 'https://x.com/kiryucoco',
    youtube: 'https://www.youtube.com/channel/UCS9uQI-jC3DE0L4IpXyvr6w',
  },
  {
    key: 'watame',
    name: '角巻わため',
    debuts: [{ date: '2019-12-29', description: 'デビュー日' }],
    birthday: '6/6',
    height: 151,
    other: '',
    group: '4期生',
    company: 'hololive',
    sort: 104.02,
    twitter: 'https://x.com/tsunomakiwatame',
    youtube: 'https://www.youtube.com/channel/UCqm3BQLlJfvkTsX_hvm0UmA',
  },
  {
    key: 'towa',
    name: '常闇トワ',
    debuts: [{ date: '2020-01-03', description: 'デビュー日' }],
    birthday: '8/8',
    height: 150,
    other: '',
    group: '4期生',
    company: 'hololive',
    sort: 104.03,
    twitter: 'https://x.com/tokoyamitowa',
    youtube: 'https://www.youtube.com/channel/UC1uv2Oq6kNxgATlCiez59hw',
  },
  {
    key: 'luna',
    name: '姫森ルーナ',
    debuts: [{ date: '2020-01-04', description: 'デビュー日' }],
    birthday: '10/10',
    height: 150,
    other: '',
    group: '4期生',
    company: 'hololive',
    sort: 104.04,
    twitter: 'https://x.com/himemoriluna',
    youtube: 'https://www.youtube.com/channel/UCa9Y57gfeY0Zro_noHRVrnw',
  },
  {
    key: 'lamy',
    name: '雪花ラミィ',
    debuts: [{ date: '2020-08-12', description: 'デビュー日' }],
    birthday: '11/15',
    height: 158,
    other: '',
    group: '5期生',
    company: 'hololive',
    sort: 105.0,
    twitter: 'https://x.com/yukihanalamy',
    youtube: 'https://www.youtube.com/channel/UCFKOVgVbGmX65RxO3EtH3iw',
  },
  {
    key: 'nene',
    name: '桃鈴ねね',
    debuts: [{ date: '2020-08-13', description: 'デビュー日' }],
    birthday: '3/2',
    height: 159,
    other: '',
    group: '5期生',
    company: 'hololive',
    sort: 105.01,
    twitter: 'https://x.com/momosuzunene',
    youtube: 'https://www.youtube.com/channel/UCAWSyEs_Io8MtpY3m-zqILA',
  },
  {
    key: 'botan',
    name: '獅白ぼたん',
    debuts: [{ date: '2020-08-14', description: 'デビュー日' }],
    birthday: '9/8',
    height: 166,
    other: '',
    group: '5期生',
    company: 'hololive',
    sort: 105.02,
    twitter: 'https://x.com/shishirobotan',
    youtube: 'https://www.youtube.com/channel/UCUKD-uaobj9jiqB-VXt71mA',
  },
  {
    key: 'polka',
    name: '尾丸ポルカ',
    debuts: [{ date: '2020-08-16', description: 'デビュー日' }],
    birthday: '1/30',
    height: 153,
    other: '',
    group: '5期生',
    company: 'hololive',
    sort: 105.03,
    twitter: 'https://x.com/omarupolka',
    youtube: 'https://www.youtube.com/channel/UCK9V2B22uJYu3N7eR_BT9QA',
  },
  {
    key: 'la-darknesss',
    name: 'ラプラス・ダークネス',
    debuts: [{ date: '2021-11-26', description: 'デビュー日' }],
    birthday: '5/25',
    height: 139,
    other: '秘密結社holoXの総帥',
    group: '6期生',
    company: 'hololive',
    sort: 106.0,
    twitter: 'https://x.com/LaplusDarknesss',
    youtube: 'https://www.youtube.com/channel/UCENwRMx5Yh42zWpzURebzTw',
  },
  {
    key: 'takane-lui',
    name: '鷹嶺ルイ',
    debuts: [{ date: '2021-11-27', description: 'デビュー日' }],
    birthday: '6/11',
    height: 161,
    other: '秘密結社holoXの女幹部',
    group: '6期生',
    company: 'hololive',
    sort: 106.01,
    twitter: 'https://x.com/takanelui',
    youtube: 'https://www.youtube.com/channel/UCs9_O1tRPMQTHQ-N_L6FU2g',
  },
  {
    key: 'hakui-koyori',
    name: '博衣こより',
    debuts: [{ date: '2021-11-28', description: 'デビュー日' }],
    birthday: '3/15',
    height: 153,
    other: '秘密結社holoXの研究者',
    group: '6期生',
    company: 'hololive',
    sort: 106.02,
    twitter: 'https://x.com/hakuikoyori',
    youtube: 'https://www.youtube.com/channel/UC6eWCld0KwmyHFbAqK3V-Rw',
  },
  {
    key: 'sakamata-chloe',
    name: '沙花叉クロヱ',
    debuts: [{ date: '2021-11-29', description: 'デビュー日' }],
    graduation: '2025-01-26',
    birthday: '5/18',
    height: 148,
    other: '秘密結社holoXの掃除屋・インターン生',
    group: '6期生',
    company: 'hololive',
    sort: 106.03,
    twitter: 'https://x.com/sakamatachloe',
    youtube: 'https://www.youtube.com/channel/UCIBY1ollUsauvVi4hW4cumw',
  },
  {
    key: 'kazama-iroha',
    name: '風真いろは',
    debuts: [{ date: '2021-11-30', description: 'デビュー日' }],
    birthday: '6/18',
    height: 156,
    other: '秘密結社holoXの用心棒',
    group: '6期生',
    company: 'hololive',
    sort: 106.04,
    twitter: 'https://x.com/kazamairohach',
    youtube: 'https://www.youtube.com/channel/UC_vMYWcDjmfdpH6r4TTn1MQ',
  },
  {
    key: 'hiodoshi-ao',
    name: '火威青',
    debuts: [{ date: '2023-09-09 20:00', description: 'デビュー日' }],
    birthday: '2/27',
    height: 171,
    other: '',
    group: 'DEV_IS ReGLOSS',
    company: 'hololive',
    sort: 107.0,
    twitter: 'https://x.com/hiodoshiao',
    youtube: 'https://www.youtube.com/@HiodoshiAo',
  },
  {
    key: 'otonose-kanade',
    name: '音乃瀬奏',
    debuts: [{ date: '2023-09-09 20:30', description: 'デビュー日' }],
    birthday: '4/20',
    height: 153,
    other: '',
    group: 'DEV_IS ReGLOSS',
    company: 'hololive',
    sort: 107.01,
    twitter: 'https://x.com/otonosekanade',
    youtube: 'https://www.youtube.com/@OtonoseKanade',
  },
  {
    key: 'ichijou-ririka',
    name: '一条莉々華',
    debuts: [{ date: '2023-09-09 21:00', description: 'デビュー日' }],
    birthday: '5/12',
    height: 162,
    other: '',
    group: 'DEV_IS ReGLOSS',
    company: 'hololive',
    sort: 107.02,
    twitter: 'https://x.com/ichijouririka',
    youtube: 'https://www.youtube.com/@IchijouRirika',
  },
  {
    key: 'juufuutei-raden',
    name: '儒烏風亭らでん',
    debuts: [{ date: '2023-09-10 20:00', description: 'デビュー日' }],
    birthday: '2/4',
    height: 159,
    other: '',
    group: 'DEV_IS ReGLOSS',
    company: 'hololive',
    sort: 107.03,
    twitter: 'https://x.com/juufuuteiraden',
    youtube: 'https://www.youtube.com/@JuufuuteiRaden',
  },
  {
    key: 'todoroki-hajime',
    name: '轟はじめ',
    debuts: [{ date: '2023-09-10 20:30', description: 'デビュー日' }],
    birthday: '6/7',
    height: 155,
    other: '',
    group: 'DEV_IS ReGLOSS',
    company: 'hololive',
    sort: 107.04,
    twitter: 'https://x.com/todoroki_hajime',
    youtube: 'https://www.youtube.com/@TodorokiHajime',
  },
  {
    key: 'isakiriona',
    name: '響咲 リオナ',
    debuts: [{ date: '2024-11-09 20:00', description: 'デビュー日' }],
    birthday: '5/29',
    height: 160,
    other: '',
    group: 'DEV_IS FLOW GLOW',
    company: 'hololive',
    sort: 108.0,
    twitter: 'https://x.com/isakiriona',
    youtube: 'https://www.youtube.com/@IsakiRiona',
  },
  {
    key: 'koganeiniko',
    name: '虎金妃笑虎',
    debuts: [{ date: '2024-11-09 20:30', description: 'デビュー日' }],
    birthday: '7/25',
    height: 172,
    other: '',
    group: 'DEV_IS FLOW GLOW',
    company: 'hololive',
    sort: 108.01,
    twitter: 'https://x.com/koganeiniko',
    youtube: 'https://www.youtube.com/@KoganeiNiko',
  },
  {
    key: 'mizumiya_su',
    name: '水宮枢',
    debuts: [{ date: '2024-11-09 21:00', description: 'デビュー日' }],
    birthday: '6/16',
    height: 151,
    other: '',
    group: 'DEV_IS FLOW GLOW',
    company: 'hololive',
    sort: 108.02,
    twitter: 'https://x.com/mizumiya_su',
    youtube: 'https://www.youtube.com/@MizumiyaSu',
  },
  {
    key: 'rindochihaya',
    name: '輪堂千速',
    debuts: [{ date: '2024-11-09 21:30', description: 'デビュー日' }],
    birthday: '7/8',
    height: 168,
    other: '',
    group: 'DEV_IS FLOW GLOW',
    company: 'hololive',
    sort: 108.03,
    twitter: 'https://x.com/rindochihaya',
    youtube: 'https://www.youtube.com/@RindoChihaya',
  },
  {
    key: 'kikiraravivi',
    name: '綺々羅々ヴィヴィ',
    debuts: [{ date: '2024-11-09 22:00', description: 'デビュー日' }],
    birthday: '8/27',
    height: 161,
    other: '',
    group: 'DEV_IS FLOW GLOW',
    company: 'hololive',
    sort: 108.04,
    twitter: 'https://x.com/kikiraravivi',
    youtube: 'https://www.youtube.com/@KikiraraVivi',
  },
  {
    key: 'yuki_sakuna',
    name: '結城さくな',
    debuts: [{ date: '2024-10-27', description: 'デビュー日' }],
    birthday: '12/2',
    height: 148,
    other: '10000歳',
    group: '個人勢',
    company: 'individual',
    sort: 0.0,
    twitter: 'https://x.com/yuki_sakuna',
    youtube: 'https://www.youtube.com/channel/UCrV1Hf5r8P148idjoSfrGEQ',
  },
  {
    key: 'kurageu_roa',
    name: '海月雲ろあ',
    debuts: [{ date: '2025-07-20', description: 'デビュー日' }],
    birthday: '11/3',
    height: 145,
    other: '',
    group: '個人勢',
    company: 'individual',
    sort: 0.01,
    twitter: 'https://x.com/kurageuroa',
    youtube: 'https://www.youtube.com/@KurageuRoa',
  },
  {
    key: 'amagai_ruka',
    name: '雨海ルカ',
    debuts: [{ date: '2025-04-27', description: 'デビュー日' }],
    birthday: '10/6',
    height: 162,
    other: '',
    group: '個人勢',
    company: 'individual',
    sort: 0.02,
    twitter: 'https://x.com/amagai_ruka',
    youtube: 'https://www.youtube.com/channel/UClS3cnIUM9yzsBPQzeyX_8Q',
  },
    {
    key: 'hanamiya_rica',
    name: '花宮莉歌',
    debuts: [{ date: '2024-10-31', description: 'デビュー日' }],
    birthday: '7/28',
    height: 154,
    other: '',
    group: '個人勢',
    company: 'individual',
    sort: 0.03,
    twitter: 'https://x.com/hanamiya_rica',
    youtube: 'https://www.youtube.com/channel/UCz4jhqrCfthF8NnldZeK_rw',
  },
  {
    key: 'kson',
    name: 'kson',
    debuts: [{ date: '2021-10-16', description: 'デビュー日' }],
    birthday: '11/1',
    height: 189.3,
    other: '総長',
    group: '個人勢',
    company: 'individual',
    sort: 0.04,
    twitter: 'https://x.com/ksononair',
    youtube: 'https://www.youtube.com/channel/UC9ruVYPv7yJmV0Rh0NKA-Lw',
  },
  {
    key: 'kagura_mea',
    name: '神楽めあ',
    debuts: [{ date: '2018-06-28', description: 'デビュー日' }],
    birthday: '8/2',
    height: 155,
    other: '',
    group: '個人勢',
    company: 'individual',
    sort: 1.0,
    twitter: 'https://x.com/KaguraMea_VoV',
    youtube: 'https://www.youtube.com/channel/UCWCc8tO-uUl_7SJXIKJACMw',
  },
  {
    key: 'inuyama_tamaki',
    name: '犬山たまき',
    debuts: [{ date: '2018-09-22', description: 'デビュー日' }],
    birthday: '6/1',
    height: 158,
    other: '',
    group: 'のりプロ',
    company: 'noripro',
    sort: 1.01,
    twitter: 'https://x.com/norioo_',
    youtube: 'https://www.youtube.com/channel/UC8NZiqKx6fsDT3AVcMiVFyA',
  },
  {
    key: 'ui_shig',
    name: 'しぐれうい',
    debuts: [{ date: '2018-11-02', description: 'デビュー日' }],
    birthday: '5/30',
    height: 149,
    other: '',
    group: '個人勢',
    company: 'individual',
    sort: 1.02,
    twitter: 'https://x.com/ui_shig',
    youtube: 'https://www.youtube.com/channel/UCt30jJgChL8qeT9VPadidSw',
  },
];
